services:
  backend:
    build:
      context: .
      target: development
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

  mongodb:
    image: mongo:8.0.4
    env_file: .env
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

volumes:
  mongo_data:
  mongo_config:
